# Install packages from available repositories 
---
- hosts: localhost
  becomes: yes
  tasks:
    - name: install java 17
      ansible.builtin.yum:
        name: java-17-openjdk
        state: present
    - name: install maven3.9.10
      ansible.builtin.yum:
        name: maven-3.9.10
        state: present
    - name: install git
      ansible.builtin.yum:
        name: git-2.13.0
        state: present
