# install/run commands from bash 

---
- hosts: localhost
  become: true
  tasks:
    - name: make folder
        shell: mkdir testfolder
        arg:
          creates: testfolder

    - name: enter directory and create
        shell: touch newfile.txt
        chdir: testfolder
        creates: newfile.txt
        

