# install/run commands from bash 

---
- hosts: localhost
  become: true
  tasks:
    - name: make folder
      shell: mkdir testfolder
      arg:
        creates: testfolder/

    - name: enter directory and create
      shell: 
        chdir: testfolder/
        creates: newfile.txt
        

