# install/run commands from bash 

---
- hosts: localhost
  become: true
  tasks:
    - name: make folder
      shell: mkdir testfolder
          
    - name: enter directory and create
      shell: cd testfolder && touch filename.txt
        

