# install/run commands from bash 

---
- hosts: localhost
  become: true
  tasks:
    - name: make folder
      shell: mkdir testfolder
    - name: enter to folder and create file
      shell:
        - cd testfolder
        - touch newfile.txt
        

