# install/run commands from bash 

---
- hosts: localhost
  become: true
  tasks:
    - name: Make folder
      shell: mkdir testfolder
      args:
        creates: testfolder

    - name: Enter directory and create
      shell: touch newfile.txt
      args:
        chdir: testfolder
        creates: newfile.txt

    - name: Ensures line exists in the file, if not adds it
      ansible.builtin.lineinfile:
        path: testfolder/newfile.txt
        line: "Hi I'm your friend"
        create: yes

#     shell executes rename file cmd after entering into folder   
    - name: execute commands
      shell: 
        cmd: mv newfile.txt oldfile.txt
        chdir: testfolder
        creates: oldfile.txt

#     shell expects a single multi-line string but we are providing multiple strings
#     so '|' is used to run separate cmds in one go and can't put cmds as list with '-'
#     so '>' is used to run/execute all multiple lines as one single line
    - name: Setup CentOS repository links
      shell: |
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        yum install epel-release -y

