# install/run commands from bash 

---
- hosts: localhost
  become: true
  tasks:
    - name: make folder
      shell: mkdir testfolder
    - name: enter directory
      shell: cd testfolder
        

